### ISSUE TITLE
NameError: global name 'ConnectionRefusedError' is not defined

### ISSUE THREAD

**Issue by thijstriemstra** [fdegrave/djangodoo#1]
Enabled the django app and getting this error straight away:

```
Traceback (most recent call last):
  File "/foo/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/foo/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/foo/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/foo/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/foo/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/foo/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/foo/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/foo/lib/python2.7/site-packages/djangodoo/__init__.py", line 55, in <module>
    set_odoo_client()
  File "/foo/lib/python2.7/site-packages/djangodoo/__init__.py", line 23, in set_odoo_client
    except ConnectionRefusedError:
NameError: global name 'ConnectionRefusedError' is not defined
```

**Comment by fdegrave** [comment]
Ok thanks it is fixed!

**Comment by thijstriemstra** [comment]
thanks
